# Generated by Django 2.2 on 2020-07-27 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cla_name', models.CharField(max_length=32, unique=True, verbose_name='班级名称')),
            ],
            options={
                'verbose_name': '班级名称',
                'verbose_name_plural': '班级名称',
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='类型名称')),
            ],
            options={
                'verbose_name': '授课老师',
                'verbose_name_plural': '授课老师',
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Classes', verbose_name='班级')),
            ],
            options={
                'verbose_name': '学生姓名',
                'verbose_name_plural': '学生姓名',
                'db_table': 'student',
            },
        ),
        migrations.AddField(
            model_name='classes',
            name='teacher',
            field=models.ManyToManyField(to='app01.Teacher', verbose_name='授课老师'),
        ),
    ]
